---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/reservations":
    get:
      summary: list reservations
      tags:
      - Reservations
      security:
      - bearer_auth: []
      responses:
        '200':
          description: ok
        '401':
          description: authentication failed
    post:
      summary: create reservation
      tags:
      - Reservations
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: successfully authenticated
        '422':
          description: invalid request
        '401':
          description: authentication failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                check_in:
                  type: date
                check_out:
                  type: date
                room_id:
                  type: integer
              required:
              - check_in
              - check_out
              - room_id
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete reservation
      tags:
      - Reservations
      security:
      - bearer_auth: []
      responses:
        '200':
          description: delete reservation
        '401':
          description: authentication failed
  "/api/v1/rooms":
    get:
      summary: list rooms
      tags:
      - Rooms
      security:
      - bearer_auth: []
      responses:
        '200':
          description: Return all the available rooms
        '401':
          description: authentication failed
    post:
      summary: create room
      tags:
      - Rooms
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: successfully authenticated
        '401':
          description: authentication failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                city:
                  type: string
                rate:
                  type: integer
                room_type:
                  type: string
                amenities:
                  type: string
                picture:
                  type: string
              required:
              - name
              - city
              - rate
              - room_type
              - amenities
              - picture
  "/api/v1/rooms/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show room
      tags:
      - Rooms
      security:
      - bearer_auth: []
      responses:
        '204':
          description: Not Found
    delete:
      summary: delete room
      tags:
      - Rooms
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: https://premium-hotel.herokuapp.com/
